# Generated by Django 4.1 on 2024-02-26 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businessUnit', '0003_remove_businessunit_business_description'),
        ('fund', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnitInFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_units', models.ManyToManyField(to='businessUnit.businessunit')),
                ('fund_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund.fund')),
            ],
        ),
    ]
