# Generated by Django 4.1 on 2024-02-28 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0003_businessunitinfund'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return_fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fund_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund.fund')),
            ],
        ),
    ]
