# Generated by Django 4.1 on 2024-02-29 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0004_return_fund'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Return_fund',
        ),
    ]
