# Generated by Django 5.0.2 on 2024-02-20 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businessUnit', '0003_remove_businessunit_business_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.IntegerField()),
                ('activity', models.CharField(max_length=50)),
                ('profit_center', models.CharField(max_length=50)),
                ('covered', models.DateField()),
                ('date_requested', models.DateField()),
                ('descriptions', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('uom', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_manager', to=settings.AUTH_USER_MODEL)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessUnit.businessunit')),
                ('encoded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encoder', to=settings.AUTH_USER_MODEL)),
                ('release_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custodian', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_controller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
