# Generated by Django 4.1 on 2024-03-04 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import forms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allocation', '0002_initial'),
        ('businessUnit', '0003_remove_businessunit_business_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(default=forms.models.RequestForm.generate_reference_code, max_length=15, unique=True)),
                ('activity', models.CharField(max_length=50)),
                ('profit_center', models.CharField(max_length=50)),
                ('covered_from', models.DateField(default=django.utils.timezone.now)),
                ('covered_to', models.DateField()),
                ('date_requested', models.DateField()),
                ('descriptions', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('uom', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Released', 'Released'), ('Liquidated', 'Liquidated'), ('Declined', 'Declined'), ('Replenish', 'Replenish')], default='Pending', max_length=20, null=True)),
                ('with_receipt', models.DecimalField(decimal_places=2, default=None, max_digits=15, null=True)),
                ('with_out_receipt', models.DecimalField(decimal_places=2, default=None, max_digits=15, null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_manager', to=settings.AUTH_USER_MODEL)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessUnit.businessunit')),
                ('encoded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encoder', to=settings.AUTH_USER_MODEL)),
                ('fund_allocation', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='allocation.allocation')),
                ('release_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custodian', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_controller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voucher_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.requestform')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptions', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('uom', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('request_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='forms.requestform')),
            ],
        ),
        migrations.CreateModel(
            name='Excess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excess_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voucher_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.requestform')),
            ],
        ),
    ]
