# Generated by Django 4.1 on 2024-03-04 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestform',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='requestform',
            name='descriptions',
        ),
        migrations.RemoveField(
            model_name='requestform',
            name='price',
        ),
        migrations.RemoveField(
            model_name='requestform',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='requestform',
            name='status',
        ),
        migrations.RemoveField(
            model_name='requestform',
            name='uom',
        ),
    ]
