# Generated by Django 5.0.2 on 2024-02-20 06:09

import forms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='reference_no',
            field=models.CharField(default=forms.models.RequestForm.generate_reference_code, unique=True),
        ),
    ]
