# Generated by Django 5.0.2 on 2024-02-20 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_requestform_reference_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestform',
            old_name='reference_no',
            new_name='voucher_no',
        ),
    ]
