# Generated by Django 4.1 on 2024-03-04 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_remove_requestform_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestform',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=15),
        ),
        migrations.AddField(
            model_name='requestform',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Released', 'Released'), ('Liquidated', 'Liquidated'), ('Declined', 'Declined'), ('Replenish', 'Replenish')], default='Pending', max_length=20, null=True),
        ),
    ]
