# Generated by Django 5.0.2 on 2024-02-20 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_rename_reference_no_requestform_voucher_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='encoded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encoder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='release_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custodian', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='reviewed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_controller', to=settings.AUTH_USER_MODEL),
        ),
    ]
