# Generated by Django 4.1 on 2024-03-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_requestform_amount_requestform_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
