# Generated by Django 4.1 on 2024-03-08 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_alter_requestform_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='date_requested',
            field=models.DateField(auto_now_add=True),
        ),
    ]
