# Generated by Django 5.0.2 on 2024-02-20 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_alter_requestform_approved_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestform',
            old_name='covered',
            new_name='covered_to',
        ),
    ]
