# Generated by Django 5.0.2 on 2024-02-20 23:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_rename_covered_requestform_covered_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestform',
            name='covered_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
