# Generated by Django 4.1 on 2024-03-11 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_alter_requestform_date_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Released', 'Released'), ('Liquidated', 'Liquidated'), ('Declined', 'Declined'), ('Replenished', 'Replenished')], default='Pending', max_length=20, null=True),
        ),
    ]
