# Generated by Django 4.1 on 2024-02-26 00:00

from django.db import migrations, models
import forms.models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_requestform_covered_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='voucher_no',
            field=models.CharField(default=forms.models.RequestForm.generate_reference_code, max_length=15, unique=True),
        ),
    ]
