# Generated by Django 4.1 on 2024-03-11 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_alter_requestform_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excess',
            name='excess_amount',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='refund',
            name='refund_amount',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='with_out_receipt',
            field=models.DecimalField(decimal_places=0, default=None, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='with_receipt',
            field=models.DecimalField(decimal_places=0, default=None, max_digits=15, null=True),
        ),
    ]
