# Generated by Django 4.1 on 2024-03-13 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0007_alter_excess_excess_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_total_amount',
            field=models.DecimalField(decimal_places=0, default=None, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='requestform',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestform',
            name='encoded_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='requestform',
            name='receive_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestform',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestform',
            name='released_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestform',
            name='reviewed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
