# Generated by Django 4.1 on 2024-02-26 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0002_initial'),
        ('forms', '0008_requestform_fund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='fund',
            field=models.ForeignKey(default=35, on_delete=django.db.models.deletion.CASCADE, to='allocation.allocation'),
        ),
    ]
