# Generated by Django 4.1 on 2024-03-14 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_alter_requestform_approved_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='approved_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='received_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='released_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='reviewed_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
