# Generated by Django 4.1 on 2024-02-26 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_alter_requestform_fund'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestform',
            old_name='fund',
            new_name='fund_allocation',
        ),
    ]
