# Generated by Django 4.1 on 2024-03-14 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_alter_requestform_approved_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestform',
            name='receive_by',
        ),
    ]
