# Generated by Django 4.1 on 2024-02-26 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0002_initial'),
        ('forms', '0010_rename_fund_requestform_fund_allocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='fund_allocation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='allocation.allocation'),
        ),
    ]
