# Generated by Django 4.1 on 2024-02-27 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_alter_requestform_fund_allocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
