# Generated by Django 4.1 on 2024-03-14 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_remove_requestform_receive_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestform',
            name='received_date',
        ),
    ]
