# Generated by Django 4.1 on 2024-02-28 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_alter_requestform_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestform',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Pending', max_length=20, null=True),
        ),
    ]
