# Generated by Django 4.1 on 2024-03-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_remove_requestform_received_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='released_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='reviewed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
