# Generated by Django 4.1 on 2024-03-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0014_alter_requestform_reviewed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='reviewed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
