# Generated by Django 4.1 on 2024-03-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0015_alter_requestform_reviewed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Released', 'Released'), ('Liquidated', 'Liquidated'), ('Declined', 'Declined'), ('Replenished', 'Replenished'), ('Cancel', 'Cancel')], default='Pending', max_length=20, null=True),
        ),
    ]
