# Generated by Django 4.1 on 2024-03-14 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0019_remove_refund_user_remove_refund_voucher_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestform',
            name='excess',
        ),
        migrations.RemoveField(
            model_name='requestform',
            name='refund',
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_amount', models.DecimalField(decimal_places=0, max_digits=15)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voucher_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.requestform')),
            ],
        ),
        migrations.CreateModel(
            name='Excess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excess_amount', models.DecimalField(decimal_places=0, max_digits=15)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voucher_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.requestform')),
            ],
        ),
    ]
