# Generated by Django 4.1 on 2024-03-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0020_remove_requestform_excess_remove_requestform_refund_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='user',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='voucher_no',
        ),
        migrations.AddField(
            model_name='requestform',
            name='excess',
            field=models.DecimalField(decimal_places=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='requestform',
            name='refund',
            field=models.DecimalField(decimal_places=0, max_digits=15, null=True),
        ),
        migrations.DeleteModel(
            name='Excess',
        ),
        migrations.DeleteModel(
            name='Refund',
        ),
    ]
