# Generated by Django 4.1 on 2024-04-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0021_remove_refund_user_remove_refund_voucher_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='voucher_no',
            field=models.CharField(default='', max_length=15, unique=True),
        ),
    ]
