# Generated by Django 4.1 on 2024-04-01 23:40

from django.db import migrations, models
import forms.models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0023_alter_requestform_voucher_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='voucher_no',
            field=models.CharField(default=forms.models.RequestForm.generate_reference_code, max_length=15),
        ),
    ]
