# Generated by Django 4.1 on 2024-04-02 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0024_alter_requestform_voucher_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestform',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestform',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
