# Generated by Django 4.1 on 2024-04-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0025_requestform_received_by_requestform_received_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='received_by',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
