# Generated by Django 5.0.3 on 2024-04-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0026_alter_requestform_received_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_total_amount',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
    ]
