# Generated by Django 5.0.3 on 2024-04-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0027_alter_item_item_total_amount_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='excess',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='refund',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='with_out_receipt',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='with_receipt',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=15, null=True),
        ),
    ]
