# Generated by Django 5.0.3 on 2024-04-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0028_alter_requestform_amount_alter_requestform_excess_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='descriptions',
            field=models.CharField(max_length=200),
        ),
    ]
