# Generated by Django 5.0.3 on 2024-04-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0029_alter_item_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestform',
            name='liquidated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestform',
            name='replenish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestform',
            name='requested_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='descriptions',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='date_requested',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='encoded_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Released', 'Released'), ('Liquidated', 'Liquidated'), ('Declined', 'Declined'), ('Replenished', 'Replenished'), ('Cancel', 'Cancel')], default='Pending', max_length=20, null=True),
        ),
    ]
