# Generated by Django 5.0.3 on 2024-05-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0030_requestform_liquidated_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
