# Generated by Django 5.0.3 on 2025-07-27 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0031_alter_item_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='descriptions',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='encoded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encoder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='excess',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='received_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='refund',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='release_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custodian', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='requested_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_controller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Released', 'Released'), ('Liquidated', 'Liquidated'), ('Declined', 'Declined'), ('Replenished', 'Replenished'), ('Cancel', 'Cancel')], default='Pending', max_length=20, null=True),
        ),
    ]
