# Generated by Django 5.0.2 on 2024-02-15 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessUnit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessunit',
            name='business_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
