# Generated by Django 5.0.2 on 2024-02-15 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businessUnit', '0002_alter_businessunit_business_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessunit',
            name='business_description',
        ),
    ]
