# Generated by Django 5.0.2 on 2024-02-14 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessUnit', '0002_initial'),
        ('user', '0002_remove_user_businessunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCompanyRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessUnit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_BusinessUnit_relationships', to='businessUnit.businessunit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_BusinessUnit_relationships', to='user.user')),
            ],
        ),
    ]
