# Generated by Django 5.0.2 on 2024-02-15 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businessUnit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessUnit.businessunit')),
            ],
        ),
    ]
