# Generated by Django 5.0.2 on 2024-02-14 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allocation', '0001_initial'),
        ('businessUnit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='business_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessUnit.businessunit'),
        ),
    ]
