# Generated by Django 5.0.2 on 2024-02-15 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allocation', '0001_initial'),
        ('fund', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund.fund'),
        ),
    ]
