# Generated by Django 4.1 on 2024-03-05 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businessUnit', '0003_remove_businessunit_business_description'),
        ('allocation', '0003_alter_allocation_business_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='business_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessUnit.businessunit'),
        ),
    ]
