# Generated by Django 4.1 on 2024-03-11 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0004_alter_allocation_business_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
    ]
