# Generated by Django 4.1 on 2024-03-12 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0005_alter_allocation_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('business_unit', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.allocation')),
            ],
        ),
    ]
