# Generated by Django 5.0.3 on 2024-04-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0006_allocationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='allocationlog',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
