# Generated by Django 5.0.2 on 2024-02-20 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('encoder', 'Encoder'), ('cost_controller', 'Cost Controller'), ('general_manager', 'General Manager'), ('custodian', 'Custodian'), ('admin', 'Admin')], default='encoder', max_length=20),
        ),
    ]
