# Generated by Django 5.0.2 on 2024-02-21 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Encoder', 'Encoder'), ('Cost Controller', 'Cost Controller'), ('General Manager', 'General Manager'), ('Custodian', 'Custodian'), ('Admin', 'Admin')], default='Admin', max_length=20),
        ),
    ]
