# Generated by Django 4.1 on 2024-03-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Encoder', 'Encoder'), ('Cost Controller', 'Cost Controller'), ('General Manager', 'General Manager'), ('Fund Custodian', 'Fund Custodian'), ('Admin', 'Admin')], default='Admin', max_length=20),
        ),
    ]
