# Generated by Django 5.0.3 on 2024-04-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessUnit', '0003_remove_businessunit_business_description'),
        ('user', '0007_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='business_unit',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Cost Controller', 'Cost Controller'), ('Finance Manager', 'Finance Manager'), ('Fund Manager', 'Fund Manager'), ('Admin', 'Admin')], default='Admin', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='business_unit',
            field=models.ManyToManyField(blank=True, to='businessUnit.businessunit'),
        ),
    ]
