# Generated by Django 5.0.3 on 2024-04-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_user_business_unit_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Cost Controller', 'Cost Controller'), ('Finance Manager', 'Finance Manager'), ('Fund Custodian', 'Fund Custodian'), ('Admin', 'Admin')], default='Admin', max_length=20),
        ),
    ]
